package midp

import "github.com/movingwoo/wfeature/internal/jvm"

// The MIDP class surface, declared rather than compiled. Each entry is what a
// class file carried — the chain a game's instanceof reads, the members it
// links against — with the Go body of every method this layer implements
// itself. A method with no body here is either abstract, or a native the
// platform registers because its answer depends on the Host.

func definitions() []jvm.ClassDefinition {
	return []jvm.ClassDefinition{
		{
			Name:      "javax/microedition/io/Connection",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic | jvm.AccessInterface | jvm.AccessAbstract,
			Methods: []jvm.MethodDefinition{
				{Name: "close", Descriptor: "()V", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/io/IOException"}},
			},
		},
		{
			Name:      "javax/microedition/io/ConnectionNotFoundException",
			SuperName: "java/io/IOException",
			Access:    jvm.AccessPublic,
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "()V", Access: jvm.AccessPublic, Body: exceptionInit(jvm.IOExceptionClass, "()V")},
				{Name: "<init>", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic, Body: exceptionInit(jvm.IOExceptionClass, "(Ljava/lang/String;)V")},
			},
		},
		{
			Name:      "javax/microedition/io/Connector",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic,
			Fields: []jvm.FieldDefinition{
				{Name: "READ", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(1)},
				{Name: "WRITE", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(2)},
				{Name: "READ_WRITE", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(3)},
			},
			Methods: []jvm.MethodDefinition{
				{Name: "open", Descriptor: "(Ljava/lang/String;)Ljavax/microedition/io/Connection;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative, Throws: []string{"java/io/IOException"}},
				{Name: "open", Descriptor: "(Ljava/lang/String;I)Ljavax/microedition/io/Connection;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative, Throws: []string{"java/io/IOException"}},
				{Name: "open", Descriptor: "(Ljava/lang/String;IZ)Ljavax/microedition/io/Connection;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative, Throws: []string{"java/io/IOException"}},
				{Name: "openInputStream", Descriptor: "(Ljava/lang/String;)Ljava/io/InputStream;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative, Throws: []string{"java/io/IOException"}},
				{Name: "openDataInputStream", Descriptor: "(Ljava/lang/String;)Ljava/io/DataInputStream;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative, Throws: []string{"java/io/IOException"}},
				{Name: "openOutputStream", Descriptor: "(Ljava/lang/String;)Ljava/io/OutputStream;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative, Throws: []string{"java/io/IOException"}},
				{Name: "openDataOutputStream", Descriptor: "(Ljava/lang/String;)Ljava/io/DataOutputStream;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative, Throws: []string{"java/io/IOException"}},
			},
		},
		{
			Name:       "javax/microedition/io/ContentConnection",
			SuperName:  "java/lang/Object",
			Interfaces: []string{"javax/microedition/io/StreamConnection"},
			Access:     jvm.AccessPublic | jvm.AccessInterface | jvm.AccessAbstract,
			Methods: []jvm.MethodDefinition{
				{Name: "getType", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "getEncoding", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "getLength", Descriptor: "()J", Access: jvm.AccessPublic | jvm.AccessAbstract},
			},
		},
		{
			Name:       "javax/microedition/io/HttpConnection",
			SuperName:  "java/lang/Object",
			Interfaces: []string{"javax/microedition/io/ContentConnection"},
			Access:     jvm.AccessPublic | jvm.AccessInterface | jvm.AccessAbstract,
			Fields: []jvm.FieldDefinition{
				{Name: "HEAD", Descriptor: "Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.StringValue("HEAD")},
				{Name: "GET", Descriptor: "Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.StringValue("GET")},
				{Name: "POST", Descriptor: "Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.StringValue("POST")},
				{Name: "HTTP_OK", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(200)},
				{Name: "HTTP_CREATED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(201)},
				{Name: "HTTP_ACCEPTED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(202)},
				{Name: "HTTP_NOT_AUTHORITATIVE", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(203)},
				{Name: "HTTP_NO_CONTENT", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(204)},
				{Name: "HTTP_RESET", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(205)},
				{Name: "HTTP_PARTIAL", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(206)},
				{Name: "HTTP_MULT_CHOICE", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(300)},
				{Name: "HTTP_MOVED_PERM", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(301)},
				{Name: "HTTP_MOVED_TEMP", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(302)},
				{Name: "HTTP_SEE_OTHER", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(303)},
				{Name: "HTTP_NOT_MODIFIED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(304)},
				{Name: "HTTP_USE_PROXY", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(305)},
				{Name: "HTTP_TEMP_REDIRECT", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(307)},
				{Name: "HTTP_BAD_REQUEST", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(400)},
				{Name: "HTTP_UNAUTHORIZED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(401)},
				{Name: "HTTP_PAYMENT_REQUIRED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(402)},
				{Name: "HTTP_FORBIDDEN", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(403)},
				{Name: "HTTP_NOT_FOUND", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(404)},
				{Name: "HTTP_BAD_METHOD", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(405)},
				{Name: "HTTP_NOT_ACCEPTABLE", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(406)},
				{Name: "HTTP_PROXY_AUTH", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(407)},
				{Name: "HTTP_CLIENT_TIMEOUT", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(408)},
				{Name: "HTTP_CONFLICT", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(409)},
				{Name: "HTTP_GONE", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(410)},
				{Name: "HTTP_LENGTH_REQUIRED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(411)},
				{Name: "HTTP_PRECON_FAILED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(412)},
				{Name: "HTTP_ENTITY_TOO_LARGE", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(413)},
				{Name: "HTTP_REQ_TOO_LONG", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(414)},
				{Name: "HTTP_UNSUPPORTED_TYPE", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(415)},
				{Name: "HTTP_UNSUPPORTED_RANGE", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(416)},
				{Name: "HTTP_EXPECT_FAILED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(417)},
				{Name: "HTTP_INTERNAL_ERROR", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(500)},
				{Name: "HTTP_NOT_IMPLEMENTED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(501)},
				{Name: "HTTP_BAD_GATEWAY", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(502)},
				{Name: "HTTP_UNAVAILABLE", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(503)},
				{Name: "HTTP_GATEWAY_TIMEOUT", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(504)},
				{Name: "HTTP_VERSION", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(505)},
			},
			Methods: []jvm.MethodDefinition{
				{Name: "getURL", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "getProtocol", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "getHost", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "getFile", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "getRef", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "getQuery", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "getPort", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "getRequestMethod", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "getRequestProperty", Descriptor: "(Ljava/lang/String;)Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "getResponseCode", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/io/IOException"}},
				{Name: "getResponseMessage", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/io/IOException"}},
				{Name: "getExpiration", Descriptor: "()J", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/io/IOException"}},
				{Name: "getDate", Descriptor: "()J", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/io/IOException"}},
				{Name: "getLastModified", Descriptor: "()J", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/io/IOException"}},
				{Name: "getHeaderField", Descriptor: "(Ljava/lang/String;)Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/io/IOException"}},
				{Name: "getHeaderFieldInt", Descriptor: "(Ljava/lang/String;I)I", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/io/IOException"}},
				{Name: "getHeaderFieldDate", Descriptor: "(Ljava/lang/String;J)J", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/io/IOException"}},
				{Name: "getHeaderField", Descriptor: "(I)Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/io/IOException"}},
				{Name: "getHeaderFieldKey", Descriptor: "(I)Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/io/IOException"}},
				{Name: "setRequestMethod", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/io/IOException"}},
				{Name: "setRequestProperty", Descriptor: "(Ljava/lang/String;Ljava/lang/String;)V", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/io/IOException"}},
			},
		},
		{
			Name:       "javax/microedition/io/InputConnection",
			SuperName:  "java/lang/Object",
			Interfaces: []string{"javax/microedition/io/Connection"},
			Access:     jvm.AccessPublic | jvm.AccessInterface | jvm.AccessAbstract,
			Methods: []jvm.MethodDefinition{
				{Name: "openInputStream", Descriptor: "()Ljava/io/InputStream;", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/io/IOException"}},
				{Name: "openDataInputStream", Descriptor: "()Ljava/io/DataInputStream;", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/io/IOException"}},
			},
		},
		{
			Name:       "javax/microedition/io/OutputConnection",
			SuperName:  "java/lang/Object",
			Interfaces: []string{"javax/microedition/io/Connection"},
			Access:     jvm.AccessPublic | jvm.AccessInterface | jvm.AccessAbstract,
			Methods: []jvm.MethodDefinition{
				{Name: "openOutputStream", Descriptor: "()Ljava/io/OutputStream;", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/io/IOException"}},
				{Name: "openDataOutputStream", Descriptor: "()Ljava/io/DataOutputStream;", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/io/IOException"}},
			},
		},
		{
			Name:       "javax/microedition/io/SocketConnection",
			SuperName:  "java/lang/Object",
			Interfaces: []string{"javax/microedition/io/StreamConnection"},
			Access:     jvm.AccessPublic | jvm.AccessInterface | jvm.AccessAbstract,
			Fields: []jvm.FieldDefinition{
				{Name: "DELAY", Descriptor: "B", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(0)},
				{Name: "LINGER", Descriptor: "B", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(1)},
				{Name: "KEEPALIVE", Descriptor: "B", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(2)},
				{Name: "RCVBUF", Descriptor: "B", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(3)},
				{Name: "SNDBUF", Descriptor: "B", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(4)},
			},
			Methods: []jvm.MethodDefinition{
				{Name: "setSocketOption", Descriptor: "(BI)V", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/lang/IllegalArgumentException", "java/io/IOException"}},
				{Name: "getSocketOption", Descriptor: "(B)I", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/lang/IllegalArgumentException", "java/io/IOException"}},
				{Name: "getLocalAddress", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/io/IOException"}},
				{Name: "getLocalPort", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/io/IOException"}},
				{Name: "getAddress", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/io/IOException"}},
				{Name: "getPort", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/io/IOException"}},
			},
		},
		{
			Name:       "javax/microedition/io/StreamConnection",
			SuperName:  "java/lang/Object",
			Interfaces: []string{"javax/microedition/io/InputConnection", "javax/microedition/io/OutputConnection"},
			Access:     jvm.AccessPublic | jvm.AccessInterface | jvm.AccessAbstract,
		},
		{
			Name:       "javax/microedition/io/StreamConnectionNotifier",
			SuperName:  "java/lang/Object",
			Interfaces: []string{"javax/microedition/io/Connection"},
			Access:     jvm.AccessPublic | jvm.AccessInterface | jvm.AccessAbstract,
			Methods: []jvm.MethodDefinition{
				{Name: "acceptAndOpen", Descriptor: "()Ljavax/microedition/io/StreamConnection;", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"java/io/IOException"}},
			},
		},
		{
			Name:      "javax/microedition/lcdui/Alert",
			SuperName: "javax/microedition/lcdui/Screen",
			Access:    jvm.AccessPublic,
			Fields: []jvm.FieldDefinition{
				{Name: "FOREVER", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(-2)},
			},
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic, Body: alertInitTitle},
				{Name: "<init>", Descriptor: "(Ljava/lang/String;Ljava/lang/String;Ljavax/microedition/lcdui/Image;Ljavax/microedition/lcdui/AlertType;)V", Access: jvm.AccessPublic, Body: alertInit},
				{Name: "initAlert", Descriptor: "(Ljava/lang/String;Ljavax/microedition/lcdui/Image;Ljavax/microedition/lcdui/AlertType;)V", Access: jvm.AccessPrivate | jvm.AccessNative},
				{Name: "getString", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setString", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getImage", Descriptor: "()Ljavax/microedition/lcdui/Image;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setImage", Descriptor: "(Ljavax/microedition/lcdui/Image;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getType", Descriptor: "()Ljavax/microedition/lcdui/AlertType;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setType", Descriptor: "(Ljavax/microedition/lcdui/AlertType;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getTimeout", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setTimeout", Descriptor: "(I)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getDefaultTimeout", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
			},
		},
		{
			Name:      "javax/microedition/lcdui/AlertType",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic,
			Fields: []jvm.FieldDefinition{
				{Name: "INFO", Descriptor: "Ljavax/microedition/lcdui/AlertType;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal},
				{Name: "WARNING", Descriptor: "Ljavax/microedition/lcdui/AlertType;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal},
				{Name: "ERROR", Descriptor: "Ljavax/microedition/lcdui/AlertType;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal},
				{Name: "ALARM", Descriptor: "Ljavax/microedition/lcdui/AlertType;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal},
				{Name: "CONFIRMATION", Descriptor: "Ljavax/microedition/lcdui/AlertType;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal},
			},
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "()V", Access: jvm.AccessProtected, Body: emptyInit},
				{Name: "playSound", Descriptor: "(Ljavax/microedition/lcdui/Display;)Z", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "<clinit>", Descriptor: "()V", Access: jvm.AccessStatic, Body: alertTypeClassInit},
			},
		},
		{
			Name:      "javax/microedition/lcdui/Canvas",
			SuperName: "javax/microedition/lcdui/Displayable",
			Access:    jvm.AccessPublic | jvm.AccessAbstract,
			Fields: []jvm.FieldDefinition{
				{Name: "UP", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(1)},
				{Name: "LEFT", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(2)},
				{Name: "RIGHT", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(5)},
				{Name: "DOWN", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(6)},
				{Name: "FIRE", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(8)},
				{Name: "GAME_A", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(9)},
				{Name: "GAME_B", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(10)},
				{Name: "GAME_C", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(11)},
				{Name: "GAME_D", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(12)},
				{Name: "KEY_NUM0", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(48)},
				{Name: "KEY_NUM1", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(49)},
				{Name: "KEY_NUM2", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(50)},
				{Name: "KEY_NUM3", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(51)},
				{Name: "KEY_NUM4", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(52)},
				{Name: "KEY_NUM5", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(53)},
				{Name: "KEY_NUM6", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(54)},
				{Name: "KEY_NUM7", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(55)},
				{Name: "KEY_NUM8", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(56)},
				{Name: "KEY_NUM9", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(57)},
				{Name: "KEY_STAR", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(42)},
				{Name: "KEY_POUND", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(35)},
				{Name: "DEVICE_UP", Descriptor: "I", Access: jvm.AccessPrivate | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(141)},
				{Name: "DEVICE_LEFT", Descriptor: "I", Access: jvm.AccessPrivate | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(142)},
				{Name: "DEVICE_RIGHT", Descriptor: "I", Access: jvm.AccessPrivate | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(145)},
				{Name: "DEVICE_DOWN", Descriptor: "I", Access: jvm.AccessPrivate | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(146)},
				{Name: "DEVICE_FIRE", Descriptor: "I", Access: jvm.AccessPrivate | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(148)},
			},
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "()V", Access: jvm.AccessProtected, Body: emptyInit},
				{Name: "repaint", Descriptor: "()V", Access: jvm.AccessPublic | jvm.AccessFinal, Body: canvasRepaint},
				{Name: "repaint", Descriptor: "(IIII)V", Access: jvm.AccessPublic | jvm.AccessFinal | jvm.AccessNative},
				{Name: "serviceRepaints", Descriptor: "()V", Access: jvm.AccessPublic | jvm.AccessFinal | jvm.AccessNative},
				{Name: "getGameAction", Descriptor: "(I)I", Access: jvm.AccessPublic, Body: canvasGameAction},
				{Name: "getKeyCode", Descriptor: "(I)I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getKeyName", Descriptor: "(I)Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setFullScreenMode", Descriptor: "(Z)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "isDoubleBuffered", Descriptor: "()Z", Access: jvm.AccessPublic, Body: answerBool(true)},
				{Name: "hasRepeatEvents", Descriptor: "()Z", Access: jvm.AccessPublic, Body: answerBool(true)},
				{Name: "hasPointerEvents", Descriptor: "()Z", Access: jvm.AccessPublic, Body: answerBool(true)},
				{Name: "hasPointerMotionEvents", Descriptor: "()Z", Access: jvm.AccessPublic, Body: answerBool(true)},
				{Name: "paint", Descriptor: "(Ljavax/microedition/lcdui/Graphics;)V", Access: jvm.AccessProtected | jvm.AccessAbstract},
				{Name: "keyPressed", Descriptor: "(I)V", Access: jvm.AccessProtected, Body: ignore},
				{Name: "keyReleased", Descriptor: "(I)V", Access: jvm.AccessProtected, Body: ignore},
				{Name: "keyRepeated", Descriptor: "(I)V", Access: jvm.AccessProtected, Body: ignore},
				{Name: "pointerPressed", Descriptor: "(II)V", Access: jvm.AccessProtected, Body: ignore},
				{Name: "pointerReleased", Descriptor: "(II)V", Access: jvm.AccessProtected, Body: ignore},
				{Name: "pointerDragged", Descriptor: "(II)V", Access: jvm.AccessProtected, Body: ignore},
			},
		},
		{
			Name:      "javax/microedition/lcdui/Choice",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic | jvm.AccessInterface | jvm.AccessAbstract,
			Fields: []jvm.FieldDefinition{
				{Name: "EXCLUSIVE", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(1)},
				{Name: "MULTIPLE", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(2)},
				{Name: "IMPLICIT", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(3)},
				{Name: "POPUP", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(4)},
				{Name: "TEXT_WRAP_DEFAULT", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(0)},
				{Name: "TEXT_WRAP_ON", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(1)},
				{Name: "TEXT_WRAP_OFF", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(2)},
			},
			Methods: []jvm.MethodDefinition{
				{Name: "size", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "getString", Descriptor: "(I)Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "getImage", Descriptor: "(I)Ljavax/microedition/lcdui/Image;", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "append", Descriptor: "(Ljava/lang/String;Ljavax/microedition/lcdui/Image;)I", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "insert", Descriptor: "(ILjava/lang/String;Ljavax/microedition/lcdui/Image;)V", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "delete", Descriptor: "(I)V", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "deleteAll", Descriptor: "()V", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "set", Descriptor: "(ILjava/lang/String;Ljavax/microedition/lcdui/Image;)V", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "isSelected", Descriptor: "(I)Z", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "getSelectedIndex", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "getSelectedFlags", Descriptor: "([Z)I", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "setSelectedIndex", Descriptor: "(IZ)V", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "setSelectedFlags", Descriptor: "([Z)V", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "setFitPolicy", Descriptor: "(I)V", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "getFitPolicy", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessAbstract},
			},
		},
		{
			Name:       "javax/microedition/lcdui/ChoiceGroup",
			SuperName:  "javax/microedition/lcdui/Item",
			Interfaces: []string{"javax/microedition/lcdui/Choice"},
			Access:     jvm.AccessPublic,
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "(Ljava/lang/String;I)V", Access: jvm.AccessPublic, Body: choiceInitEmpty(ChoiceGroupClass)},
				{Name: "<init>", Descriptor: "(Ljava/lang/String;I[Ljava/lang/String;[Ljavax/microedition/lcdui/Image;)V", Access: jvm.AccessPublic, Body: choiceInit(ChoiceGroupClass, false)},
				{Name: "initChoice", Descriptor: "(I)V", Access: jvm.AccessNative},
				{Name: "size", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getString", Descriptor: "(I)Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getImage", Descriptor: "(I)Ljavax/microedition/lcdui/Image;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "append", Descriptor: "(Ljava/lang/String;Ljavax/microedition/lcdui/Image;)I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "insert", Descriptor: "(ILjava/lang/String;Ljavax/microedition/lcdui/Image;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "delete", Descriptor: "(I)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "deleteAll", Descriptor: "()V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "set", Descriptor: "(ILjava/lang/String;Ljavax/microedition/lcdui/Image;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "isSelected", Descriptor: "(I)Z", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getSelectedIndex", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getSelectedFlags", Descriptor: "([Z)I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setSelectedIndex", Descriptor: "(IZ)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setSelectedFlags", Descriptor: "([Z)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setFitPolicy", Descriptor: "(I)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getFitPolicy", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setFont", Descriptor: "(ILjavax/microedition/lcdui/Font;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getFont", Descriptor: "(I)Ljavax/microedition/lcdui/Font;", Access: jvm.AccessPublic | jvm.AccessNative},
			},
		},
		{
			Name:      "javax/microedition/lcdui/Command",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic,
			Fields: []jvm.FieldDefinition{
				{Name: "SCREEN", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(1)},
				{Name: "BACK", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(2)},
				{Name: "CANCEL", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(3)},
				{Name: "OK", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(4)},
				{Name: "HELP", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(5)},
				{Name: "STOP", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(6)},
				{Name: "EXIT", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(7)},
				{Name: "ITEM", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(8)},
			},
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "(Ljava/lang/String;II)V", Access: jvm.AccessPublic, Body: commandInit(true)},
				{Name: "<init>", Descriptor: "(Ljava/lang/String;Ljava/lang/String;II)V", Access: jvm.AccessPublic, Body: commandInit(false)},
				{Name: "init", Descriptor: "(Ljava/lang/String;Ljava/lang/String;II)V", Access: jvm.AccessPrivate | jvm.AccessNative},
				{Name: "getLabel", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getLongLabel", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getCommandType", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getPriority", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
			},
		},
		{
			Name:      "javax/microedition/lcdui/CommandListener",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic | jvm.AccessInterface | jvm.AccessAbstract,
			Methods: []jvm.MethodDefinition{
				{Name: "commandAction", Descriptor: "(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V", Access: jvm.AccessPublic | jvm.AccessAbstract},
			},
		},
		{
			Name:      "javax/microedition/lcdui/Display",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic,
			Methods: []jvm.MethodDefinition{
				{Name: "getDisplay", Descriptor: "(Ljavax/microedition/midlet/MIDlet;)Ljavax/microedition/lcdui/Display;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative},
				{Name: "getCurrent", Descriptor: "()Ljavax/microedition/lcdui/Displayable;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setCurrent", Descriptor: "(Ljavax/microedition/lcdui/Displayable;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "callSerially", Descriptor: "(Ljava/lang/Runnable;)V", Access: jvm.AccessPublic | jvm.AccessNative},
			},
		},
		{
			Name:      "javax/microedition/lcdui/Displayable",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic | jvm.AccessAbstract,
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "()V", Access: jvm.AccessProtected, Body: emptyInit},
				{Name: "getWidth", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getHeight", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "isShown", Descriptor: "()Z", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "addCommand", Descriptor: "(Ljavax/microedition/lcdui/Command;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "removeCommand", Descriptor: "(Ljavax/microedition/lcdui/Command;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setCommandListener", Descriptor: "(Ljavax/microedition/lcdui/CommandListener;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getTitle", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setTitle", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getTicker", Descriptor: "()Ljavax/microedition/lcdui/Ticker;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setTicker", Descriptor: "(Ljavax/microedition/lcdui/Ticker;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "sizeChanged", Descriptor: "(II)V", Access: jvm.AccessProtected, Body: ignore},
			},
		},
		{
			Name:      "javax/microedition/lcdui/Font",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic | jvm.AccessFinal,
			Fields: []jvm.FieldDefinition{
				{Name: "FACE_SYSTEM", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(0)},
				{Name: "FACE_MONOSPACE", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(32)},
				{Name: "FACE_PROPORTIONAL", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(64)},
				{Name: "STYLE_PLAIN", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(0)},
				{Name: "STYLE_BOLD", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(1)},
				{Name: "STYLE_ITALIC", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(2)},
				{Name: "STYLE_UNDERLINED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(4)},
				{Name: "SIZE_MEDIUM", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(0)},
				{Name: "SIZE_SMALL", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(8)},
				{Name: "SIZE_LARGE", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(16)},
				{Name: "FONT_STATIC_TEXT", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(0)},
				{Name: "FONT_INPUT_TEXT", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(1)},
			},
			Methods: []jvm.MethodDefinition{
				{Name: "getDefaultFont", Descriptor: "()Ljavax/microedition/lcdui/Font;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative},
				{Name: "getFont", Descriptor: "(I)Ljavax/microedition/lcdui/Font;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative},
				{Name: "getFont", Descriptor: "(III)Ljavax/microedition/lcdui/Font;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative},
				{Name: "getFace", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getStyle", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getSize", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "isPlain", Descriptor: "()Z", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "isBold", Descriptor: "()Z", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "isItalic", Descriptor: "()Z", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "isUnderlined", Descriptor: "()Z", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getHeight", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getBaselinePosition", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "charWidth", Descriptor: "(C)I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "charsWidth", Descriptor: "([CII)I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "stringWidth", Descriptor: "(Ljava/lang/String;)I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "substringWidth", Descriptor: "(Ljava/lang/String;II)I", Access: jvm.AccessPublic | jvm.AccessNative},
			},
		},
		{
			Name:      "javax/microedition/lcdui/Form",
			SuperName: "javax/microedition/lcdui/Screen",
			Access:    jvm.AccessPublic,
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic, Body: formInitTitle},
				{Name: "<init>", Descriptor: "(Ljava/lang/String;[Ljavax/microedition/lcdui/Item;)V", Access: jvm.AccessPublic, Body: formInitItems},
				{Name: "append", Descriptor: "(Ljavax/microedition/lcdui/Item;)I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "append", Descriptor: "(Ljava/lang/String;)I", Access: jvm.AccessPublic, Body: formAppendString},
				{Name: "append", Descriptor: "(Ljavax/microedition/lcdui/Image;)I", Access: jvm.AccessPublic, Body: formAppendImage},
				{Name: "insert", Descriptor: "(ILjavax/microedition/lcdui/Item;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "delete", Descriptor: "(I)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "deleteAll", Descriptor: "()V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "set", Descriptor: "(ILjavax/microedition/lcdui/Item;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "get", Descriptor: "(I)Ljavax/microedition/lcdui/Item;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "size", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setItemStateListener", Descriptor: "(Ljavax/microedition/lcdui/ItemStateListener;)V", Access: jvm.AccessPublic | jvm.AccessNative},
			},
		},
		{
			Name:      "javax/microedition/lcdui/Graphics",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic | jvm.AccessFinal,
			Fields: []jvm.FieldDefinition{
				{Name: "HCENTER", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(1)},
				{Name: "VCENTER", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(2)},
				{Name: "LEFT", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(4)},
				{Name: "RIGHT", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(8)},
				{Name: "TOP", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(16)},
				{Name: "BOTTOM", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(32)},
				{Name: "BASELINE", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(64)},
			},
			Methods: []jvm.MethodDefinition{
				{Name: "getFont", Descriptor: "()Ljavax/microedition/lcdui/Font;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setFont", Descriptor: "(Ljavax/microedition/lcdui/Font;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setColor", Descriptor: "(I)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setColor", Descriptor: "(III)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getColor", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setClip", Descriptor: "(IIII)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "clipRect", Descriptor: "(IIII)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getClipX", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getClipY", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getClipWidth", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getClipHeight", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "translate", Descriptor: "(II)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getTranslateX", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getTranslateY", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "fillRect", Descriptor: "(IIII)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "drawLine", Descriptor: "(IIII)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "drawRect", Descriptor: "(IIII)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "fillRoundRect", Descriptor: "(IIIIII)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "drawRoundRect", Descriptor: "(IIIIII)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "fillArc", Descriptor: "(IIIIII)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "drawArc", Descriptor: "(IIIIII)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "drawImage", Descriptor: "(Ljavax/microedition/lcdui/Image;III)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "drawRegion", Descriptor: "(Ljavax/microedition/lcdui/Image;IIIIIIII)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "drawRGB", Descriptor: "([IIIIIIIZ)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "drawChar", Descriptor: "(CIII)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "drawChars", Descriptor: "([CIIIII)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "drawString", Descriptor: "(Ljava/lang/String;III)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "drawSubstring", Descriptor: "(Ljava/lang/String;IIIII)V", Access: jvm.AccessPublic | jvm.AccessNative},
			},
		},
		{
			Name:      "javax/microedition/lcdui/Image",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic,
			Methods: []jvm.MethodDefinition{
				{Name: "createImage", Descriptor: "(II)Ljavax/microedition/lcdui/Image;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative},
				{Name: "createImage", Descriptor: "(Ljavax/microedition/lcdui/Image;)Ljavax/microedition/lcdui/Image;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative},
				{Name: "createImage", Descriptor: "(Ljavax/microedition/lcdui/Image;IIIII)Ljavax/microedition/lcdui/Image;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative},
				{Name: "createImage", Descriptor: "(Ljava/lang/String;)Ljavax/microedition/lcdui/Image;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative, Throws: []string{"java/io/IOException"}},
				{Name: "createImage", Descriptor: "([BII)Ljavax/microedition/lcdui/Image;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative},
				{Name: "createRGBImage", Descriptor: "([IIIZ)Ljavax/microedition/lcdui/Image;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative},
				{Name: "getGraphics", Descriptor: "()Ljavax/microedition/lcdui/Graphics;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getWidth", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getHeight", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "isMutable", Descriptor: "()Z", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getRGB", Descriptor: "([IIIIIII)V", Access: jvm.AccessPublic | jvm.AccessNative},
			},
		},
		{
			Name:      "javax/microedition/lcdui/ImageItem",
			SuperName: "javax/microedition/lcdui/Item",
			Access:    jvm.AccessPublic,
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "(Ljava/lang/String;Ljavax/microedition/lcdui/Image;ILjava/lang/String;)V", Access: jvm.AccessPublic, Body: imageItemInit},
				{Name: "<init>", Descriptor: "(Ljava/lang/String;Ljavax/microedition/lcdui/Image;ILjava/lang/String;I)V", Access: jvm.AccessPublic, Body: imageItemInitAppearance},
				{Name: "initImage", Descriptor: "(Ljavax/microedition/lcdui/Image;Ljava/lang/String;)V", Access: jvm.AccessPrivate | jvm.AccessNative},
				{Name: "getImage", Descriptor: "()Ljavax/microedition/lcdui/Image;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setImage", Descriptor: "(Ljavax/microedition/lcdui/Image;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getAltText", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setAltText", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getAppearanceMode", Descriptor: "()I", Access: jvm.AccessPublic, Body: answerInt(itemPlain)},
			},
		},
		{
			Name:      "javax/microedition/lcdui/Item",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic | jvm.AccessAbstract,
			Fields: []jvm.FieldDefinition{
				{Name: "LAYOUT_DEFAULT", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(0)},
				{Name: "LAYOUT_LEFT", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(1)},
				{Name: "LAYOUT_RIGHT", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(2)},
				{Name: "LAYOUT_CENTER", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(3)},
				{Name: "LAYOUT_TOP", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(16)},
				{Name: "LAYOUT_BOTTOM", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(32)},
				{Name: "LAYOUT_VCENTER", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(48)},
				{Name: "LAYOUT_NEWLINE_BEFORE", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(256)},
				{Name: "LAYOUT_NEWLINE_AFTER", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(512)},
				{Name: "LAYOUT_SHRINK", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(1024)},
				{Name: "LAYOUT_EXPAND", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(2048)},
				{Name: "LAYOUT_VSHRINK", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(4096)},
				{Name: "LAYOUT_VEXPAND", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(8192)},
				{Name: "LAYOUT_2", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(16384)},
				{Name: "PLAIN", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(0)},
				{Name: "HYPERLINK", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(1)},
				{Name: "BUTTON", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(2)},
			},
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "()V", Access: jvm.AccessProtected, Body: itemInit},
				{Name: "initItem", Descriptor: "()V", Access: jvm.AccessNative},
				{Name: "getLabel", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setLabel", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getLayout", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setLayout", Descriptor: "(I)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "addCommand", Descriptor: "(Ljavax/microedition/lcdui/Command;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "removeCommand", Descriptor: "(Ljavax/microedition/lcdui/Command;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setDefaultCommand", Descriptor: "(Ljavax/microedition/lcdui/Command;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setItemCommandListener", Descriptor: "(Ljavax/microedition/lcdui/ItemCommandListener;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getPreferredWidth", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getPreferredHeight", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getMinimumWidth", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getMinimumHeight", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setPreferredSize", Descriptor: "(II)V", Access: jvm.AccessPublic, Body: ignore},
				{Name: "notifyStateChanged", Descriptor: "()V", Access: jvm.AccessPublic | jvm.AccessNative},
			},
		},
		{
			Name:      "javax/microedition/lcdui/ItemCommandListener",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic | jvm.AccessInterface | jvm.AccessAbstract,
			Methods: []jvm.MethodDefinition{
				{Name: "commandAction", Descriptor: "(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Item;)V", Access: jvm.AccessPublic | jvm.AccessAbstract},
			},
		},
		{
			Name:      "javax/microedition/lcdui/ItemStateListener",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic | jvm.AccessInterface | jvm.AccessAbstract,
			Methods: []jvm.MethodDefinition{
				{Name: "itemStateChanged", Descriptor: "(Ljavax/microedition/lcdui/Item;)V", Access: jvm.AccessPublic | jvm.AccessAbstract},
			},
		},
		{
			Name:       "javax/microedition/lcdui/List",
			SuperName:  "javax/microedition/lcdui/Screen",
			Interfaces: []string{"javax/microedition/lcdui/Choice"},
			Access:     jvm.AccessPublic,
			Fields: []jvm.FieldDefinition{
				{Name: "SELECT_COMMAND", Descriptor: "Ljavax/microedition/lcdui/Command;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal},
			},
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "(Ljava/lang/String;I)V", Access: jvm.AccessPublic, Body: choiceInitEmpty(ListClass)},
				{Name: "<init>", Descriptor: "(Ljava/lang/String;I[Ljava/lang/String;[Ljavax/microedition/lcdui/Image;)V", Access: jvm.AccessPublic, Body: choiceInit(ListClass, true)},
				{Name: "initChoice", Descriptor: "(I)V", Access: jvm.AccessNative},
				{Name: "size", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getString", Descriptor: "(I)Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getImage", Descriptor: "(I)Ljavax/microedition/lcdui/Image;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "append", Descriptor: "(Ljava/lang/String;Ljavax/microedition/lcdui/Image;)I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "insert", Descriptor: "(ILjava/lang/String;Ljavax/microedition/lcdui/Image;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "delete", Descriptor: "(I)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "deleteAll", Descriptor: "()V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "set", Descriptor: "(ILjava/lang/String;Ljavax/microedition/lcdui/Image;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "isSelected", Descriptor: "(I)Z", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getSelectedIndex", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getSelectedFlags", Descriptor: "([Z)I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setSelectedIndex", Descriptor: "(IZ)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setSelectedFlags", Descriptor: "([Z)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setFitPolicy", Descriptor: "(I)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getFitPolicy", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setSelectCommand", Descriptor: "(Ljavax/microedition/lcdui/Command;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setFont", Descriptor: "(ILjavax/microedition/lcdui/Font;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getFont", Descriptor: "(I)Ljavax/microedition/lcdui/Font;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "<clinit>", Descriptor: "()V", Access: jvm.AccessStatic, Body: listClassInit},
			},
		},
		{
			Name:      "javax/microedition/lcdui/Screen",
			SuperName: "javax/microedition/lcdui/Displayable",
			Access:    jvm.AccessPublic | jvm.AccessAbstract,
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "()V", Access: jvm.AccessProtected, Body: emptyInit},
			},
		},
		{
			Name:      "javax/microedition/lcdui/StringItem",
			SuperName: "javax/microedition/lcdui/Item",
			Access:    jvm.AccessPublic,
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "(Ljava/lang/String;Ljava/lang/String;)V", Access: jvm.AccessPublic, Body: stringItemInit},
				{Name: "<init>", Descriptor: "(Ljava/lang/String;Ljava/lang/String;I)V", Access: jvm.AccessPublic, Body: stringItemInitAppearance},
				{Name: "initText", Descriptor: "(Ljava/lang/String;I)V", Access: jvm.AccessPrivate | jvm.AccessNative},
				{Name: "getText", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setText", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getAppearanceMode", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setFont", Descriptor: "(Ljavax/microedition/lcdui/Font;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getFont", Descriptor: "()Ljavax/microedition/lcdui/Font;", Access: jvm.AccessPublic | jvm.AccessNative},
			},
		},
		{
			Name:      "javax/microedition/lcdui/TextBox",
			SuperName: "javax/microedition/lcdui/Screen",
			Access:    jvm.AccessPublic,
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "(Ljava/lang/String;Ljava/lang/String;II)V", Access: jvm.AccessPublic, Body: textInit(TextBoxClass, true)},
				{Name: "initText", Descriptor: "(Ljava/lang/String;II)V", Access: jvm.AccessPrivate | jvm.AccessNative},
				{Name: "getString", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setString", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getChars", Descriptor: "([C)I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setChars", Descriptor: "([CII)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "insert", Descriptor: "(Ljava/lang/String;I)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "delete", Descriptor: "(II)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "size", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getMaxSize", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setMaxSize", Descriptor: "(I)I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getCaretPosition", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setConstraints", Descriptor: "(I)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getConstraints", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setInitialInputMode", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic, Body: ignore},
			},
		},
		{
			Name:      "javax/microedition/lcdui/TextField",
			SuperName: "javax/microedition/lcdui/Item",
			Access:    jvm.AccessPublic,
			Fields: []jvm.FieldDefinition{
				{Name: "ANY", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(0)},
				{Name: "EMAILADDR", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(1)},
				{Name: "NUMERIC", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(2)},
				{Name: "PHONENUMBER", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(3)},
				{Name: "URL", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(4)},
				{Name: "DECIMAL", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(5)},
				{Name: "PASSWORD", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(65536)},
				{Name: "UNEDITABLE", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(131072)},
				{Name: "SENSITIVE", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(262144)},
				{Name: "NON_PREDICTIVE", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(524288)},
				{Name: "INITIAL_CAPS_WORD", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(1048576)},
				{Name: "INITIAL_CAPS_SENTENCE", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(2097152)},
				{Name: "CONSTRAINT_MASK", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(65535)},
			},
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "(Ljava/lang/String;Ljava/lang/String;II)V", Access: jvm.AccessPublic, Body: textInit(TextFieldClass, false)},
				{Name: "initText", Descriptor: "(Ljava/lang/String;II)V", Access: jvm.AccessPrivate | jvm.AccessNative},
				{Name: "getString", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setString", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getChars", Descriptor: "([C)I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setChars", Descriptor: "([CII)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "insert", Descriptor: "(Ljava/lang/String;I)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "delete", Descriptor: "(II)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "size", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getMaxSize", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setMaxSize", Descriptor: "(I)I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getCaretPosition", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setConstraints", Descriptor: "(I)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getConstraints", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setInitialInputMode", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic, Body: ignore},
			},
		},
		{
			Name:      "javax/microedition/lcdui/Ticker",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic,
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic, Body: tickerInit},
				{Name: "init", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPrivate | jvm.AccessNative},
				{Name: "getString", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setString", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic | jvm.AccessNative},
			},
		},
		{
			Name:      "javax/microedition/lcdui/game/GameCanvas",
			SuperName: "javax/microedition/lcdui/Canvas",
			Access:    jvm.AccessPublic | jvm.AccessAbstract,
			Fields: []jvm.FieldDefinition{
				{Name: "UP_PRESSED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(2)},
				{Name: "DOWN_PRESSED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(64)},
				{Name: "LEFT_PRESSED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(4)},
				{Name: "RIGHT_PRESSED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(32)},
				{Name: "FIRE_PRESSED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(256)},
				{Name: "GAME_A_PRESSED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(512)},
				{Name: "GAME_B_PRESSED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(1024)},
				{Name: "GAME_C_PRESSED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(2048)},
				{Name: "GAME_D_PRESSED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(4096)},
			},
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "(Z)V", Access: jvm.AccessProtected, Body: gameCanvasInit},
				{Name: "initBuffer", Descriptor: "(Z)V", Access: jvm.AccessPrivate | jvm.AccessNative},
				{Name: "getGraphics", Descriptor: "()Ljavax/microedition/lcdui/Graphics;", Access: jvm.AccessProtected | jvm.AccessNative},
				{Name: "getKeyStates", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "flushGraphics", Descriptor: "()V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "flushGraphics", Descriptor: "(IIII)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "paint", Descriptor: "(Ljavax/microedition/lcdui/Graphics;)V", Access: jvm.AccessProtected, Body: gameCanvasPaint},
				{Name: "drawBuffer", Descriptor: "(Ljavax/microedition/lcdui/Graphics;)V", Access: jvm.AccessPrivate | jvm.AccessNative},
			},
		},
		{
			Name:      "javax/microedition/media/Manager",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic,
			Fields: []jvm.FieldDefinition{
				{Name: "TONE_DEVICE_LOCATOR", Descriptor: "Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.StringValue("device://tone")},
			},
			Methods: []jvm.MethodDefinition{
				{Name: "createPlayer", Descriptor: "(Ljava/io/InputStream;Ljava/lang/String;)Ljavax/microedition/media/Player;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative, Throws: []string{"java/io/IOException", "javax/microedition/media/MediaException"}},
				{Name: "createPlayer", Descriptor: "(Ljava/lang/String;)Ljavax/microedition/media/Player;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative, Throws: []string{"java/io/IOException", "javax/microedition/media/MediaException"}},
				{Name: "playTone", Descriptor: "(III)V", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative, Throws: []string{"javax/microedition/media/MediaException"}},
				{Name: "getSupportedContentTypes", Descriptor: "(Ljava/lang/String;)[Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative},
				{Name: "getSupportedProtocols", Descriptor: "(Ljava/lang/String;)[Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative},
			},
		},
		{
			Name:      "javax/microedition/media/MediaException",
			SuperName: "java/lang/Exception",
			Access:    jvm.AccessPublic,
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "()V", Access: jvm.AccessPublic, Body: exceptionInit("java/lang/Exception", "()V")},
				{Name: "<init>", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic, Body: exceptionInit("java/lang/Exception", "(Ljava/lang/String;)V")},
			},
		},
		{
			Name:      "javax/microedition/media/Player",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic,
			Fields: []jvm.FieldDefinition{
				{Name: "UNREALIZED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(100)},
				{Name: "REALIZED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(200)},
				{Name: "PREFETCHED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(300)},
				{Name: "STARTED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(400)},
				{Name: "CLOSED", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(0)},
				{Name: "TIME_UNKNOWN", Descriptor: "J", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.LongValue(-1)},
			},
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "()V", Access: 0, Body: emptyInit},
				{Name: "realize", Descriptor: "()V", Access: jvm.AccessPublic | jvm.AccessNative, Throws: []string{"javax/microedition/media/MediaException"}},
				{Name: "prefetch", Descriptor: "()V", Access: jvm.AccessPublic | jvm.AccessNative, Throws: []string{"javax/microedition/media/MediaException"}},
				{Name: "start", Descriptor: "()V", Access: jvm.AccessPublic | jvm.AccessNative, Throws: []string{"javax/microedition/media/MediaException"}},
				{Name: "stop", Descriptor: "()V", Access: jvm.AccessPublic | jvm.AccessNative, Throws: []string{"javax/microedition/media/MediaException"}},
				{Name: "deallocate", Descriptor: "()V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "close", Descriptor: "()V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getState", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getDuration", Descriptor: "()J", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getMediaTime", Descriptor: "()J", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "setMediaTime", Descriptor: "(J)J", Access: jvm.AccessPublic | jvm.AccessNative, Throws: []string{"javax/microedition/media/MediaException"}},
				{Name: "setLoopCount", Descriptor: "(I)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "getContentType", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "addPlayerListener", Descriptor: "(Ljavax/microedition/media/PlayerListener;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "removePlayerListener", Descriptor: "(Ljavax/microedition/media/PlayerListener;)V", Access: jvm.AccessPublic | jvm.AccessNative},
			},
		},
		{
			Name:      "javax/microedition/media/PlayerListener",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic | jvm.AccessInterface | jvm.AccessAbstract,
			Fields: []jvm.FieldDefinition{
				{Name: "STARTED", Descriptor: "Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.StringValue("started")},
				{Name: "STOPPED", Descriptor: "Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.StringValue("stopped")},
				{Name: "END_OF_MEDIA", Descriptor: "Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.StringValue("endOfMedia")},
				{Name: "DURATION_UPDATED", Descriptor: "Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.StringValue("durationUpdated")},
				{Name: "DEVICE_UNAVAILABLE", Descriptor: "Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.StringValue("deviceUnavailable")},
				{Name: "DEVICE_AVAILABLE", Descriptor: "Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.StringValue("deviceAvailable")},
				{Name: "VOLUME_CHANGED", Descriptor: "Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.StringValue("volumeChanged")},
				{Name: "CLOSED", Descriptor: "Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.StringValue("closed")},
				{Name: "ERROR", Descriptor: "Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.StringValue("error")},
			},
			Methods: []jvm.MethodDefinition{
				{Name: "playerUpdate", Descriptor: "(Ljavax/microedition/media/Player;Ljava/lang/String;Ljava/lang/Object;)V", Access: jvm.AccessPublic | jvm.AccessAbstract},
			},
		},
		{
			Name:      "javax/microedition/midlet/MIDlet",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic | jvm.AccessAbstract,
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "()V", Access: jvm.AccessProtected, Body: emptyInit},
				{Name: "startApp", Descriptor: "()V", Access: jvm.AccessProtected | jvm.AccessAbstract, Throws: []string{"javax/microedition/midlet/MIDletStateChangeException"}},
				{Name: "pauseApp", Descriptor: "()V", Access: jvm.AccessProtected | jvm.AccessAbstract},
				{Name: "destroyApp", Descriptor: "(Z)V", Access: jvm.AccessProtected | jvm.AccessAbstract, Throws: []string{"javax/microedition/midlet/MIDletStateChangeException"}},
				{Name: "getAppProperty", Descriptor: "(Ljava/lang/String;)Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessFinal | jvm.AccessNative},
				{Name: "notifyDestroyed", Descriptor: "()V", Access: jvm.AccessPublic | jvm.AccessFinal | jvm.AccessNative},
				{Name: "notifyPaused", Descriptor: "()V", Access: jvm.AccessPublic | jvm.AccessFinal | jvm.AccessNative},
				{Name: "resumeRequest", Descriptor: "()V", Access: jvm.AccessPublic | jvm.AccessFinal | jvm.AccessNative},
			},
		},
		{
			Name:      "javax/microedition/midlet/MIDletStateChangeException",
			SuperName: "java/lang/Exception",
			Access:    jvm.AccessPublic,
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "()V", Access: jvm.AccessPublic, Body: exceptionInit("java/lang/Exception", "()V")},
				{Name: "<init>", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic, Body: exceptionInit("java/lang/Exception", "(Ljava/lang/String;)V")},
			},
		},
		{
			Name:      "javax/microedition/rms/InvalidRecordIDException",
			SuperName: "javax/microedition/rms/RecordStoreException",
			Access:    jvm.AccessPublic,
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "()V", Access: jvm.AccessPublic, Body: exceptionInit(RecordStoreExceptionClass, "()V")},
				{Name: "<init>", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic, Body: exceptionInit(RecordStoreExceptionClass, "(Ljava/lang/String;)V")},
			},
		},
		{
			Name:      "javax/microedition/rms/RecordComparator",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic | jvm.AccessInterface | jvm.AccessAbstract,
			Fields: []jvm.FieldDefinition{
				{Name: "EQUIVALENT", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(0)},
				{Name: "FOLLOWS", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(1)},
				{Name: "PRECEDES", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(-1)},
			},
			Methods: []jvm.MethodDefinition{
				{Name: "compare", Descriptor: "([B[B)I", Access: jvm.AccessPublic | jvm.AccessAbstract},
			},
		},
		{
			Name:      "javax/microedition/rms/RecordEnumeration",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic | jvm.AccessInterface | jvm.AccessAbstract,
			Methods: []jvm.MethodDefinition{
				{Name: "numRecords", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "nextRecord", Descriptor: "()[B", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"javax/microedition/rms/InvalidRecordIDException", "javax/microedition/rms/RecordStoreNotOpenException", "javax/microedition/rms/RecordStoreException"}},
				{Name: "nextRecordId", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"javax/microedition/rms/InvalidRecordIDException"}},
				{Name: "previousRecord", Descriptor: "()[B", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"javax/microedition/rms/InvalidRecordIDException", "javax/microedition/rms/RecordStoreNotOpenException", "javax/microedition/rms/RecordStoreException"}},
				{Name: "previousRecordId", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessAbstract, Throws: []string{"javax/microedition/rms/InvalidRecordIDException"}},
				{Name: "hasNextElement", Descriptor: "()Z", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "hasPreviousElement", Descriptor: "()Z", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "reset", Descriptor: "()V", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "rebuild", Descriptor: "()V", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "keepUpdated", Descriptor: "(Z)V", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "isKeptUpdated", Descriptor: "()Z", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "destroy", Descriptor: "()V", Access: jvm.AccessPublic | jvm.AccessAbstract},
			},
		},
		{
			Name:      "javax/microedition/rms/RecordFilter",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic | jvm.AccessInterface | jvm.AccessAbstract,
			Methods: []jvm.MethodDefinition{
				{Name: "matches", Descriptor: "([B)Z", Access: jvm.AccessPublic | jvm.AccessAbstract},
			},
		},
		{
			Name:      "javax/microedition/rms/RecordListener",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic | jvm.AccessInterface | jvm.AccessAbstract,
			Methods: []jvm.MethodDefinition{
				{Name: "recordAdded", Descriptor: "(Ljavax/microedition/rms/RecordStore;I)V", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "recordChanged", Descriptor: "(Ljavax/microedition/rms/RecordStore;I)V", Access: jvm.AccessPublic | jvm.AccessAbstract},
				{Name: "recordDeleted", Descriptor: "(Ljavax/microedition/rms/RecordStore;I)V", Access: jvm.AccessPublic | jvm.AccessAbstract},
			},
		},
		{
			// Package-private: a game reaches the enumeration through the
			// RecordEnumeration interface enumerateRecords answers with.
			Name:       "javax/microedition/rms/RecordSet",
			SuperName:  "java/lang/Object",
			Interfaces: []string{"javax/microedition/rms/RecordEnumeration", "javax/microedition/rms/RecordListener"},
			Access:     0,
			Fields: []jvm.FieldDefinition{
				{Name: "store", Descriptor: "Ljavax/microedition/rms/RecordStore;", Access: jvm.AccessPrivate},
				{Name: "filter", Descriptor: "Ljavax/microedition/rms/RecordFilter;", Access: jvm.AccessPrivate},
				{Name: "comparator", Descriptor: "Ljavax/microedition/rms/RecordComparator;", Access: jvm.AccessPrivate},
				{Name: "updated", Descriptor: "Z", Access: jvm.AccessPrivate},
				{Name: "destroyed", Descriptor: "Z", Access: jvm.AccessPrivate},
				{Name: "ids", Descriptor: "[I", Access: jvm.AccessPrivate},
				{Name: "position", Descriptor: "I", Access: jvm.AccessPrivate},
			},
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "(Ljavax/microedition/rms/RecordStore;Ljavax/microedition/rms/RecordFilter;Ljavax/microedition/rms/RecordComparator;Z)V", Access: 0, Body: recordSetInit},
				{Name: "numRecords", Descriptor: "()I", Access: jvm.AccessPublic, Body: recordSetNumRecords},
				{Name: "nextRecord", Descriptor: "()[B", Access: jvm.AccessPublic, Throws: []string{"javax/microedition/rms/InvalidRecordIDException", "javax/microedition/rms/RecordStoreNotOpenException", "javax/microedition/rms/RecordStoreException"}, Body: recordSetRecord("nextRecordId")},
				{Name: "nextRecordId", Descriptor: "()I", Access: jvm.AccessPublic, Throws: []string{"javax/microedition/rms/InvalidRecordIDException"}, Body: recordSetNextRecordID},
				{Name: "previousRecord", Descriptor: "()[B", Access: jvm.AccessPublic, Throws: []string{"javax/microedition/rms/InvalidRecordIDException", "javax/microedition/rms/RecordStoreNotOpenException", "javax/microedition/rms/RecordStoreException"}, Body: recordSetRecord("previousRecordId")},
				{Name: "previousRecordId", Descriptor: "()I", Access: jvm.AccessPublic, Throws: []string{"javax/microedition/rms/InvalidRecordIDException"}, Body: recordSetPreviousRecordID},
				{Name: "hasNextElement", Descriptor: "()Z", Access: jvm.AccessPublic, Body: recordSetHasElement(true)},
				{Name: "hasPreviousElement", Descriptor: "()Z", Access: jvm.AccessPublic, Body: recordSetHasElement(false)},
				{Name: "reset", Descriptor: "()V", Access: jvm.AccessPublic, Body: recordSetReset},
				{Name: "rebuild", Descriptor: "()V", Access: jvm.AccessPublic, Body: recordSetRebuild},
				{Name: "keepUpdated", Descriptor: "(Z)V", Access: jvm.AccessPublic, Body: recordSetKeepUpdated},
				{Name: "isKeptUpdated", Descriptor: "()Z", Access: jvm.AccessPublic, Body: recordSetIsKeptUpdated},
				{Name: "destroy", Descriptor: "()V", Access: jvm.AccessPublic, Body: recordSetDestroy},
				{Name: "recordAdded", Descriptor: "(Ljavax/microedition/rms/RecordStore;I)V", Access: jvm.AccessPublic, Body: recordSetChanged},
				{Name: "recordChanged", Descriptor: "(Ljavax/microedition/rms/RecordStore;I)V", Access: jvm.AccessPublic, Body: recordSetChanged},
				{Name: "recordDeleted", Descriptor: "(Ljavax/microedition/rms/RecordStore;I)V", Access: jvm.AccessPublic, Body: recordSetChanged},
			},
		},
		{
			Name:      "javax/microedition/rms/RecordStore",
			SuperName: "java/lang/Object",
			Access:    jvm.AccessPublic,
			Fields: []jvm.FieldDefinition{
				{Name: "AUTHMODE_PRIVATE", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(0)},
				{Name: "AUTHMODE_ANY", Descriptor: "I", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessFinal, Constant: jvm.IntValue(1)},
			},
			Methods: []jvm.MethodDefinition{
				{Name: "listRecordStores", Descriptor: "()[Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative},
				{Name: "openRecordStore", Descriptor: "(Ljava/lang/String;Z)Ljavax/microedition/rms/RecordStore;", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative, Throws: []string{"javax/microedition/rms/RecordStoreException", "javax/microedition/rms/RecordStoreNotFoundException", "javax/microedition/rms/RecordStoreFullException"}},
				{Name: "openRecordStore", Descriptor: "(Ljava/lang/String;ZIZ)Ljavax/microedition/rms/RecordStore;", Access: jvm.AccessPublic | jvm.AccessStatic, Throws: []string{"javax/microedition/rms/RecordStoreException", "javax/microedition/rms/RecordStoreNotFoundException", "javax/microedition/rms/RecordStoreFullException"}, Body: openRecordStoreAuthorized},
				{Name: "openRecordStore", Descriptor: "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljavax/microedition/rms/RecordStore;", Access: jvm.AccessPublic | jvm.AccessStatic, Throws: []string{"javax/microedition/rms/RecordStoreException", "javax/microedition/rms/RecordStoreNotFoundException"}, Body: openRecordStoreFromSuite},
				{Name: "deleteRecordStore", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic | jvm.AccessStatic | jvm.AccessNative, Throws: []string{"javax/microedition/rms/RecordStoreException", "javax/microedition/rms/RecordStoreNotFoundException"}},
				{Name: "setMode", Descriptor: "(IZ)V", Access: jvm.AccessPublic, Throws: []string{"javax/microedition/rms/RecordStoreException"}, Body: recordStoreSetMode},
				{Name: "closeRecordStore", Descriptor: "()V", Access: jvm.AccessPublic | jvm.AccessNative, Throws: []string{"javax/microedition/rms/RecordStoreException", "javax/microedition/rms/RecordStoreNotOpenException"}},
				{Name: "getName", Descriptor: "()Ljava/lang/String;", Access: jvm.AccessPublic | jvm.AccessNative, Throws: []string{"javax/microedition/rms/RecordStoreNotOpenException"}},
				{Name: "getVersion", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative, Throws: []string{"javax/microedition/rms/RecordStoreNotOpenException"}},
				{Name: "getNumRecords", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative, Throws: []string{"javax/microedition/rms/RecordStoreNotOpenException"}},
				{Name: "getSize", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative, Throws: []string{"javax/microedition/rms/RecordStoreNotOpenException"}},
				{Name: "getSizeAvailable", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative, Throws: []string{"javax/microedition/rms/RecordStoreNotOpenException"}},
				{Name: "getLastModified", Descriptor: "()J", Access: jvm.AccessPublic | jvm.AccessNative, Throws: []string{"javax/microedition/rms/RecordStoreNotOpenException"}},
				{Name: "getNextRecordID", Descriptor: "()I", Access: jvm.AccessPublic | jvm.AccessNative, Throws: []string{"javax/microedition/rms/RecordStoreNotOpenException", "javax/microedition/rms/RecordStoreException"}},
				{Name: "addRecord", Descriptor: "([BII)I", Access: jvm.AccessPublic | jvm.AccessNative, Throws: []string{"javax/microedition/rms/RecordStoreNotOpenException", "javax/microedition/rms/RecordStoreException", "javax/microedition/rms/RecordStoreFullException"}},
				{Name: "deleteRecord", Descriptor: "(I)V", Access: jvm.AccessPublic | jvm.AccessNative, Throws: []string{"javax/microedition/rms/RecordStoreNotOpenException", "javax/microedition/rms/InvalidRecordIDException", "javax/microedition/rms/RecordStoreException"}},
				{Name: "getRecordSize", Descriptor: "(I)I", Access: jvm.AccessPublic | jvm.AccessNative, Throws: []string{"javax/microedition/rms/RecordStoreNotOpenException", "javax/microedition/rms/InvalidRecordIDException", "javax/microedition/rms/RecordStoreException"}},
				{Name: "getRecord", Descriptor: "(I[BI)I", Access: jvm.AccessPublic | jvm.AccessNative, Throws: []string{"javax/microedition/rms/RecordStoreNotOpenException", "javax/microedition/rms/InvalidRecordIDException", "javax/microedition/rms/RecordStoreException"}},
				{Name: "getRecord", Descriptor: "(I)[B", Access: jvm.AccessPublic | jvm.AccessNative, Throws: []string{"javax/microedition/rms/RecordStoreNotOpenException", "javax/microedition/rms/InvalidRecordIDException", "javax/microedition/rms/RecordStoreException"}},
				{Name: "setRecord", Descriptor: "(I[BII)V", Access: jvm.AccessPublic | jvm.AccessNative, Throws: []string{"javax/microedition/rms/RecordStoreNotOpenException", "javax/microedition/rms/InvalidRecordIDException", "javax/microedition/rms/RecordStoreException", "javax/microedition/rms/RecordStoreFullException"}},
				{Name: "addRecordListener", Descriptor: "(Ljavax/microedition/rms/RecordListener;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "removeRecordListener", Descriptor: "(Ljavax/microedition/rms/RecordListener;)V", Access: jvm.AccessPublic | jvm.AccessNative},
				{Name: "enumerateRecords", Descriptor: "(Ljavax/microedition/rms/RecordFilter;Ljavax/microedition/rms/RecordComparator;Z)Ljavax/microedition/rms/RecordEnumeration;", Access: jvm.AccessPublic, Throws: []string{"javax/microedition/rms/RecordStoreNotOpenException"}, Body: recordStoreEnumerate},
				{Name: "recordIds", Descriptor: "()[I", Access: jvm.AccessNative, Throws: []string{"javax/microedition/rms/RecordStoreNotOpenException"}},
				{Name: "checkOpen", Descriptor: "()V", Access: jvm.AccessPrivate | jvm.AccessNative, Throws: []string{"javax/microedition/rms/RecordStoreNotOpenException"}},
			},
		},
		{
			Name:      "javax/microedition/rms/RecordStoreException",
			SuperName: "java/lang/Exception",
			Access:    jvm.AccessPublic,
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "()V", Access: jvm.AccessPublic, Body: exceptionInit("java/lang/Exception", "()V")},
				{Name: "<init>", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic, Body: exceptionInit("java/lang/Exception", "(Ljava/lang/String;)V")},
			},
		},
		{
			Name:      "javax/microedition/rms/RecordStoreFullException",
			SuperName: "javax/microedition/rms/RecordStoreException",
			Access:    jvm.AccessPublic,
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "()V", Access: jvm.AccessPublic, Body: exceptionInit(RecordStoreExceptionClass, "()V")},
				{Name: "<init>", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic, Body: exceptionInit(RecordStoreExceptionClass, "(Ljava/lang/String;)V")},
			},
		},
		{
			Name:      "javax/microedition/rms/RecordStoreNotFoundException",
			SuperName: "javax/microedition/rms/RecordStoreException",
			Access:    jvm.AccessPublic,
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "()V", Access: jvm.AccessPublic, Body: exceptionInit(RecordStoreExceptionClass, "()V")},
				{Name: "<init>", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic, Body: exceptionInit(RecordStoreExceptionClass, "(Ljava/lang/String;)V")},
			},
		},
		{
			Name:      "javax/microedition/rms/RecordStoreNotOpenException",
			SuperName: "javax/microedition/rms/RecordStoreException",
			Access:    jvm.AccessPublic,
			Methods: []jvm.MethodDefinition{
				{Name: "<init>", Descriptor: "()V", Access: jvm.AccessPublic, Body: exceptionInit(RecordStoreExceptionClass, "()V")},
				{Name: "<init>", Descriptor: "(Ljava/lang/String;)V", Access: jvm.AccessPublic, Body: exceptionInit(RecordStoreExceptionClass, "(Ljava/lang/String;)V")},
			},
		},
	}
}
