package skt

import (
	"fmt"
	"slices"

	"github.com/movingwoo/wfeature/internal/backend"
	"github.com/movingwoo/wfeature/internal/jvm"
)

const (
	maxMediaPlayers    = 256
	maxPlayerListeners = 256
	maxPlayerEvents    = 4096
)

// playerEvent holds the objects needed for deferred delivery. Checkpoints
// retain these references rather than a Go closure or a running callback.
type playerEvent struct {
	Player    *jvm.Object
	Name      string
	Data      *jvm.Object
	Listeners []*jvm.Object
}

func (runtime *Runtime) registerMediaPlayer(handle backend.AudioHandle, object *jvm.Object) error {
	if handle == 0 || object == nil {
		return fmt.Errorf("media player registration requires a handle and object")
	}
	runtime.mediaMu.Lock()
	defer runtime.mediaMu.Unlock()
	if _, exists := runtime.mediaPlayers[handle]; exists {
		return fmt.Errorf("media player handle %d is already registered", handle)
	}
	for _, existing := range runtime.mediaPlayers {
		if existing == object {
			return fmt.Errorf("media player object is already registered")
		}
	}
	if len(runtime.mediaPlayers) >= maxMediaPlayers {
		return fmt.Errorf("media player count exceeds %d", maxMediaPlayers)
	}
	if runtime.mediaPlayers == nil {
		runtime.mediaPlayers = make(map[backend.AudioHandle]*jvm.Object)
	}
	runtime.mediaPlayers[handle] = object
	return nil
}

func (runtime *Runtime) unregisterMediaPlayer(handle backend.AudioHandle) {
	runtime.mediaMu.Lock()
	delete(runtime.mediaPlayers, handle)
	runtime.mediaMu.Unlock()
}

func (runtime *Runtime) mediaPlayerSnapshot() []*jvm.Object {
	runtime.mediaMu.Lock()
	defer runtime.mediaMu.Unlock()
	handles := make([]backend.AudioHandle, 0, len(runtime.mediaPlayers))
	for handle := range runtime.mediaPlayers {
		handles = append(handles, handle)
	}
	slices.Sort(handles)
	players := make([]*jvm.Object, len(handles))
	for i, handle := range handles {
		players[i] = runtime.mediaPlayers[handle]
	}
	return players
}

// queuePlayerEventLocked requires player.mu. Recording the listener snapshot
// before that lock is released keeps events in the order of their transitions.
func (runtime *Runtime) queuePlayerEventLocked(object *jvm.Object, player *playerData, event string, data *jvm.Object) error {
	if object == nil || player == nil || event == "" {
		return fmt.Errorf("media event requires a player and name")
	}
	if len(player.listeners) > maxPlayerListeners {
		return fmt.Errorf("media player listener count exceeds %d", maxPlayerListeners)
	}
	if len(player.listeners) == 0 {
		return nil
	}
	runtime.mediaMu.Lock()
	defer runtime.mediaMu.Unlock()
	if len(runtime.mediaEvents) >= maxPlayerEvents {
		return fmt.Errorf("pending media event count exceeds %d", maxPlayerEvents)
	}
	runtime.mediaEvents = append(runtime.mediaEvents, playerEvent{
		Player: object, Name: event, Data: data, Listeners: slices.Clone(player.listeners),
	})
	return nil
}

// drainPlayerEvents requires dispatchMu. Swap the queue before entering Java
// so events generated by listeners wait for the next Host pass.
func (runtime *Runtime) drainPlayerEvents() error {
	if runtime.State() != StateActive {
		return nil
	}
	runtime.mediaMu.Lock()
	events := runtime.mediaEvents
	runtime.mediaEvents = nil
	runtime.mediaMu.Unlock()
	for _, event := range events {
		if code, ok := wipiPlaybackEvent(event.Name); ok {
			if err := runtime.deliverWIPIEvent(event, code); err != nil {
				return err
			}
			continue
		}
		name, err := runtime.VM.InternString(event.Name)
		if err != nil {
			return fmt.Errorf("create media event string: %w", err)
		}
		for _, listener := range event.Listeners {
			if listener == nil {
				return fmt.Errorf("media event %s has a null listener", event.Name)
			}
			_, err := runtime.VM.InvokeVirtual(listener, "playerUpdate",
				"(Ljavax/microedition/media/Player;Ljava/lang/String;Ljava/lang/Object;)V",
				jvm.ReferenceValue(event.Player), jvm.ReferenceValue(name),
				jvm.ReferenceValue(event.Data))
			if absorbed := runtime.absorbUncaughtCallback("playerUpdate "+listener.ClassName, err); absorbed != nil {
				return fmt.Errorf("deliver playerUpdate %s: %w", event.Name, absorbed)
			}
		}
	}
	return nil
}
