// Opt-in browser integration against a release server and an authored fixture.
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdirSync, copyFileSync, rmSync, writeFileSync } from "node:fs";
import { resolve, join } from "node:path";
import { pathToFileURL } from "node:url";
import net from "node:net";

const [binary, engineName = "chromium"] = process.argv.slice(2);
if (!binary || !process.env.PLAYWRIGHT_MODULE) throw new Error("Usage: PLAYWRIGHT_MODULE=/path/to/playwright/index.mjs node web/acceptance/rapid-fire.mjs SERVER [chromium|webkit]");
const { [engineName]: engine } = await import(pathToFileURL(resolve(process.env.PLAYWRIGHT_MODULE)));
const run = `rapid-fire-${engineName}-${Date.now()}`;
const output = resolve("var/acceptance", run);
const games = resolve("var/games", `.${run}`);
const ext = resolve("var/ext", run);
const saves = resolve("var/savedata", run);
for (const path of [output, games, ext, saves]) mkdirSync(path, { recursive: true });
mkdirSync(join(games, "library"));
copyFileSync("internal/platform/skt/testdata/canvas-skt.zip", join(games, "library", "canvas.zip"));
const listener = net.createServer();
await new Promise(done => listener.listen(0, "127.0.0.1", done));
const port = listener.address().port;
await new Promise(done => listener.close(done));
const origin = `http://127.0.0.1:${port}`;
const server = spawn(resolve(binary), ["-addr", `127.0.0.1:${port}`, "-games", games, "-ext", ext,
  "-saves", saves, "-logs", join(output, "logs"), "-web", join(output, "no-external-web"), "-open=false"]);
let logs = "", browser;
server.stdout.on("data", data => { logs += data; });
server.stderr.on("data", data => { logs += data; });
const pause = ms => new Promise(done => setTimeout(done, ms));
const result = { engine: engineName, checks: [], errors: [], counts: {} };
try {
  for (let i = 0; ; i++) {
    try { if ((await fetch(`${origin}/api/status`)).ok) break; } catch {}
    if (i === 100 || server.exitCode !== null) throw new Error("server did not start");
    await pause(50);
  }
  browser = await engine.launch({ headless: true });
  const context = await browser.newContext({ viewport: { width: 1280, height: 1000 }, hasTouch: true });
  await context.addInitScript(() => {
    window.rapidMessages = [];
    const send = WebSocket.prototype.send;
    WebSocket.prototype.send = function(data) {
      try { const message = JSON.parse(data); if (message.kind === "key") window.rapidMessages.push({ ...message, time: performance.now() }); } catch {}
      return send.call(this, data);
    };
  });
  const page = await context.newPage();
  page.on("pageerror", error => result.errors.push(error.message));
  page.on("websocket", socket => socket.on("framereceived", event => {
    if (typeof event.payload !== "string") return;
    const message = JSON.parse(event.payload);
    if (message.kind === "error") result.errors.push(message.message);
  }));
  await page.goto(origin);
  await page.locator("#game-start").click();
  await page.waitForFunction(() => !document.querySelector("#restart").classList.contains("hidden"));
  if (!await page.locator("#settings-panel").evaluate(element => element.classList.contains("visible"))) await page.locator("#settings-toggle").click();
  await page.locator("#keypad-arrange-open").click();
  await page.locator('[data-cell="pad-r1c1"]').click();
  await page.locator("#keypad-arrange-keys").getByRole("button", { name: "연사", exact: true }).click();
  await page.locator("#keypad-arrange-close").click();
  const toggle = page.locator('button[data-cell="pad-r1c1"][data-key="RAPID_FIRE"]');
  assert.equal(await toggle.textContent(), "연사 off");
  result.checks.push("switch assigned through keypad editor");
  const clear = () => page.evaluate(() => { window.rapidMessages = []; });
  const messages = () => page.evaluate(() => window.rapidMessages);
  await pause(2000);
  await toggle.click();
  await clear();
  await page.keyboard.down("w");
  await pause(1000);
  await page.keyboard.up("w");
  let sent = await messages();
  let presses = sent.filter(message => message.action === "press");
  assert.ok(presses.length >= 2 && presses.length <= 11, JSON.stringify({sent, mode: (await toggle.textContent()).split(" ").at(-1), errors: result.errors}));
  assert.ok(sent.every(message => message.code === 53));
  assert.equal(sent.at(-1).action, "release");
  result.counts.manual = presses.length;
  result.checks.push("manual keyboard hold with bounded repeat cadence");
  await toggle.click();
  await clear(); await pause(200); assert.deepEqual(await messages(), []);
  result.checks.push("auto waits for a target key");
  await page.keyboard.press("Space");
  await clear();
  await pause(1000);
  sent = await messages();
  presses = sent.filter(message => message.action === "press");
  assert.ok(presses.length >= 2 && presses.length <= 11, JSON.stringify({sent, mode: (await toggle.textContent()).split(" ").at(-1), errors: result.errors}));
  assert.ok(sent.every(message => message.code === 148));
  result.counts.auto = presses.length;
  result.checks.push("auto OK continues after key release");
  const tapFive = page.locator('button[data-key="5"]').first();
  await tapFive.click();
  await clear(); await pause(500);
  sent = await messages();
  assert.ok(sent.some(message => message.action === "press"));
  assert.ok(sent.every(message => message.code === 53));
  await tapFive.click();
  await clear(); await pause(200); assert.deepEqual(await messages(), []);
  await tapFive.click();
  await page.keyboard.press("Space");
  await clear(); await pause(500);
  sent = await messages();
  assert.ok(sent.some(message => message.action === "press"));
  assert.ok(sent.every(message => message.code === 148));
  await page.keyboard.press("Space");
  await clear(); await pause(200); assert.deepEqual(await messages(), []);
  result.checks.push("auto switches both ways and toggles each target off");
  await page.keyboard.press("Space");
  await page.evaluate(() => window.dispatchEvent(new Event("blur")));
  assert.equal(await toggle.textContent(), "연사 off");
  await clear(); await pause(200); assert.deepEqual(await messages(), []);
  result.checks.push("focus loss releases and stops auto");
  await toggle.click();
  await clear();
  const five = page.locator('button[data-key="5"]').first();
  const box = await five.boundingBox();
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down(); await pause(250); await page.mouse.up();
  sent = await messages();
  assert.ok(sent.filter(message => message.action === "press").length >= 2);
  assert.equal(sent.at(-1).action, "release");
  await clear(); await pause(150); assert.deepEqual(await messages(), []);
  result.checks.push("pointer hold repeats and lift stops");
  await toggle.click();
  await page.keyboard.press("Space");
  await page.locator("#keypad-arrange-open").click();
  assert.equal(await toggle.textContent(), "연사 off");
  await page.locator("#keypad-arrange-close").click();
  result.checks.push("editing resets auto");
  await toggle.click(); await toggle.click();
  await page.keyboard.press("Space");
  await page.locator("#restart").click();
  await page.locator("#confirm-accept").click();
  await page.locator("#game-start").click();
  await page.waitForFunction(() => !document.querySelector("#restart").classList.contains("hidden"));
  assert.equal(await toggle.textContent(), "연사 off");
  result.checks.push("new game starts off and retains switch placement");
  await page.setViewportSize({ width: 390, height: 844 });
  await pause(350);
  await page.screenshot({ path: join(output, "mobile-keypad.png") });
  assert.deepEqual(result.errors, []);
  console.log(JSON.stringify(result, null, 2));
} finally {
  await browser?.close();
  server.kill("SIGTERM");
  await new Promise(done => { if (server.exitCode !== null) done(); else server.once("exit", done); });
  writeFileSync(join(output, "result.json"), JSON.stringify(result, null, 2));
  writeFileSync(join(output, "server.log"), logs);
  rmSync(ext, { recursive: true, force: true });
}
