// Command javastub writes the runtime's class surface out as Java source
// stubs, so a test fixture can be compiled against this emulator with javac.
//
// The runtime declares its library in Go and carries no class files, which
// leaves javac with nothing to compile a fixture against. This turns the same
// declarations back into signatures: no bodies, no behavior, only the names,
// types and constants a fixture links against. The runtime, not these stubs,
// is what the fixture then runs on.
//
//	go run ./internal/tools/javastub -out /tmp/stubs
//	javac -source 1.8 -target 1.8 -g:none -cp /tmp/stubs -d "$fixture" Fixture.java
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/movingwoo/wfeature/internal/api/midp"
	"github.com/movingwoo/wfeature/internal/api/skvm"
	"github.com/movingwoo/wfeature/internal/jvm"
)

func main() {
	out := flag.String("out", "", "directory to write the stub sources into")
	flag.Parse()
	if *out == "" {
		fmt.Fprintln(os.Stderr, "javastub: -out is required")
		os.Exit(1)
	}
	if err := run(*out); err != nil {
		fmt.Fprintln(os.Stderr, "javastub:", err)
		os.Exit(1)
	}
}

func run(out string) error {
	definitions := append([]jvm.ClassDefinition(nil), jvm.CoreLibraryDefinitions()...)
	definitions = append(definitions, midp.Definitions()...)
	definitions = append(definitions, skvm.Definitions()...)
	sort.Slice(definitions, func(i, j int) bool { return definitions[i].Name < definitions[j].Name })

	for _, definition := range definitions {
		path := filepath.Join(out, filepath.FromSlash(definition.Name)+".java")
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(source(definition)), 0o644); err != nil {
			return err
		}
	}
	fmt.Fprintf(os.Stderr, "javastub: wrote %d classes to %s\n", len(definitions), out)
	return nil
}

// source renders one class. Everything that can be native is native and
// everything else is empty, because javac only has to agree about the shape.
func source(definition jvm.ClassDefinition) string {
	var builder strings.Builder
	packageName, simpleName := split(definition.Name)
	if packageName != "" {
		fmt.Fprintf(&builder, "package %s;\n\n", packageName)
	}
	fmt.Fprintf(&builder, "// Generated by internal/tools/javastub from the runtime's own class\n")
	fmt.Fprintf(&builder, "// declarations. Signatures only: the runtime holds the behavior.\n")

	isInterface := definition.Access&jvm.AccessInterface != 0
	fmt.Fprintf(&builder, "public ")
	switch {
	case isInterface:
		fmt.Fprintf(&builder, "interface %s", simpleName)
		if len(definition.Interfaces) > 0 {
			fmt.Fprintf(&builder, " extends %s", javaNames(definition.Interfaces))
		}
	default:
		if definition.Access&jvm.AccessAbstract != 0 {
			fmt.Fprintf(&builder, "abstract ")
		} else if definition.Access&jvm.AccessFinal != 0 {
			fmt.Fprintf(&builder, "final ")
		}
		fmt.Fprintf(&builder, "class %s", simpleName)
		if definition.SuperName != "" && definition.SuperName != "java/lang/Object" {
			fmt.Fprintf(&builder, " extends %s", javaName(definition.SuperName))
		}
		if len(definition.Interfaces) > 0 {
			fmt.Fprintf(&builder, " implements %s", javaNames(definition.Interfaces))
		}
	}
	fmt.Fprintf(&builder, " {\n")

	for _, field := range definition.Fields {
		if field.Access&jvm.AccessPrivate != 0 {
			continue
		}
		fmt.Fprintf(&builder, "    %s%s %s", modifiers(field.Access, isInterface), javaType(field.Descriptor), field.Name)
		if field.Access&jvm.AccessStatic != 0 && field.Access&jvm.AccessFinal != 0 {
			fmt.Fprintf(&builder, " = %s", constant(field))
		}
		fmt.Fprintf(&builder, ";\n")
	}

	for _, method := range definition.Methods {
		if method.Access&jvm.AccessPrivate != 0 || method.Name == "<clinit>" {
			continue
		}
		parameters, returns := signature(method.Descriptor)
		if method.Name == "<init>" {
			// A constructor cannot be native, and its body is what the runtime
			// replaces, so the stub's is empty.
			fmt.Fprintf(&builder, "    %s%s(%s)%s {\n    }\n",
				modifiers(method.Access, false), simpleName, parameters, throwsClause(method.Throws))
			continue
		}
		abstract := isInterface || method.Access&jvm.AccessAbstract != 0
		declaration := modifiers(method.Access, isInterface)
		if !abstract {
			declaration += "native "
		}
		fmt.Fprintf(&builder, "    %s%s %s(%s)%s;\n",
			declaration, returns, method.Name, parameters, throwsClause(method.Throws))
	}
	fmt.Fprintf(&builder, "}\n")
	return builder.String()
}

// modifiers renders the access a member is declared with. Inside an interface
// javac rejects the ones that are implied there.
func modifiers(access uint16, inInterface bool) string {
	var parts []string
	switch {
	case access&jvm.AccessPublic != 0 && !inInterface:
		parts = append(parts, "public")
	case access&jvm.AccessProtected != 0:
		parts = append(parts, "protected")
	}
	if access&jvm.AccessStatic != 0 && !inInterface {
		parts = append(parts, "static")
	}
	if access&jvm.AccessFinal != 0 && !inInterface {
		parts = append(parts, "final")
	}
	if access&jvm.AccessAbstract != 0 && !inInterface {
		parts = append(parts, "abstract")
	}
	if len(parts) == 0 {
		return ""
	}
	return strings.Join(parts, " ") + " "
}

// constant renders a static final field's initializer. A field whose value is
// an object the runtime creates has no constant to render, and null keeps the
// stub compiling: the game reads the runtime's value, not this one.
func constant(field jvm.FieldDefinition) string {
	value := field.Constant
	switch value.Kind() {
	case jvm.ValueInt:
		number, err := value.Int32()
		if err != nil {
			return "0"
		}
		switch field.Descriptor {
		case "Z":
			if number != 0 {
				return "true"
			}
			return "false"
		case "C":
			return fmt.Sprintf("(char) %d", uint16(number))
		case "B", "S":
			return fmt.Sprintf("(%s) %d", javaType(field.Descriptor), number)
		default:
			return fmt.Sprintf("%d", number)
		}
	case jvm.ValueLong:
		number, err := value.Int64()
		if err != nil {
			return "0L"
		}
		return fmt.Sprintf("%dL", number)
	case jvm.ValueFloat:
		number, err := value.Float32()
		if err != nil {
			return "0f"
		}
		return fmt.Sprintf("%vf", number)
	case jvm.ValueDouble:
		number, err := value.Float64()
		if err != nil {
			return "0d"
		}
		return fmt.Sprintf("%v", number)
	case jvm.ValueReference:
		object, err := value.Reference()
		if err == nil && object != nil {
			if text, ok := jvm.StringText(object); ok {
				return fmt.Sprintf("%q", text)
			}
		}
	}
	if field.Descriptor == "Ljava/lang/String;" || strings.HasPrefix(field.Descriptor, "L") || strings.HasPrefix(field.Descriptor, "[") {
		return "null"
	}
	return "0"
}

// signature splits a method descriptor into a Java parameter list and a
// return type. Parameters are named by position, since nothing reads them.
func signature(descriptor string) (parameters, returns string) {
	open := strings.IndexByte(descriptor, '(')
	close := strings.IndexByte(descriptor, ')')
	if open != 0 || close < 0 {
		return "", "void"
	}
	var declared []string
	rest := descriptor[1:close]
	for index := 0; len(rest) > 0; index++ {
		one, remaining := splitType(rest)
		if one == "" {
			break
		}
		declared = append(declared, fmt.Sprintf("%s argument%d", javaType(one), index))
		rest = remaining
	}
	return strings.Join(declared, ", "), javaType(descriptor[close+1:])
}

// splitType takes the first field descriptor off the front of a run of them.
func splitType(descriptor string) (one, rest string) {
	if descriptor == "" {
		return "", ""
	}
	index := 0
	for index < len(descriptor) && descriptor[index] == '[' {
		index++
	}
	if index >= len(descriptor) {
		return "", ""
	}
	if descriptor[index] == 'L' {
		end := strings.IndexByte(descriptor[index:], ';')
		if end < 0 {
			return "", ""
		}
		index += end
	}
	return descriptor[:index+1], descriptor[index+1:]
}

// javaType renders a field descriptor as the Java type it names.
func javaType(descriptor string) string {
	if strings.HasPrefix(descriptor, "[") {
		return javaType(descriptor[1:]) + "[]"
	}
	switch descriptor {
	case "V":
		return "void"
	case "Z":
		return "boolean"
	case "B":
		return "byte"
	case "C":
		return "char"
	case "S":
		return "short"
	case "I":
		return "int"
	case "J":
		return "long"
	case "F":
		return "float"
	case "D":
		return "double"
	}
	if strings.HasPrefix(descriptor, "L") && strings.HasSuffix(descriptor, ";") {
		return javaName(descriptor[1 : len(descriptor)-1])
	}
	return "Object"
}

// throwsClause renders what a method declares it can throw. Without it a
// fixture cannot catch what the runtime raises, and an override cannot declare
// the exception its supertype allows.
func throwsClause(thrown []string) string {
	if len(thrown) == 0 {
		return ""
	}
	return " throws " + javaNames(thrown)
}

func javaName(internal string) string { return strings.ReplaceAll(internal, "/", ".") }

func javaNames(internal []string) string {
	names := make([]string, 0, len(internal))
	for _, name := range internal {
		names = append(names, javaName(name))
	}
	return strings.Join(names, ", ")
}

func split(internal string) (packageName, simpleName string) {
	index := strings.LastIndexByte(internal, '/')
	if index < 0 {
		return "", internal
	}
	return javaName(internal[:index]), internal[index+1:]
}
