// Package hqx implements the hq2x, hq3x, and hq4x magnification filters.
//
// These games render 240x320. Shown at that size on a modern display they are
// a postage stamp, and scaled up by an integer factor they are a grid of large
// squares. hqx is the filter arcade emulators settled on for exactly this: it
// looks at each pixel's eight neighbours, decides which of them belong to the
// same shape, and draws the edges between shapes as diagonals rather than
// staircases. Flat areas stay flat, so the pixel art keeps its character.
//
// The 256-case decision table per filter — one case per combination of which
// neighbours differ — is the whole algorithm, and it is mechanically derived
// from Maxim Stepin's original. pattern2x.go, pattern3x.go, and pattern4x.go
// hold it, generated by translating the reference implementation case by case:
// all 256 patterns are covered exactly once in each, which is what makes the
// translation checkable rather than trusted.
//
// # Licence
//
// Those three files are a mechanical translation of the reference
// implementation's tables rather than an independent reimplementation, so they
// are a substantial portion of that work and carry its licence with them:
//
//	Copyright (c) 2017 Christopher Serr
//	Licensed under MIT OR Apache-2.0; this project relies on the MIT terms.
//
// The full text is in THIRD-PARTY-NOTICES.md, which every release binary
// carries — see internal/licenses.
package hqx

import "fmt"

// Colors are packed 0xAARRGGBB, which is what the interpolation masks below
// assume.
const (
	maskAlpha   = 0xFF000000
	maskGreen   = 0x0000FF00
	maskRedBlue = 0x00FF00FF
)

// rgbToYUV converts a color to the luma/chroma space the difference test uses.
//
// The reference implementation precomputes this into a 16-million entry table,
// which is 64MB. Three multiplies per pixel is cheaper than the cache misses
// that table costs, so the size is not even the reason to skip it.
func rgbToYUV(color uint32) uint32 {
	red := float64(color >> 16 & 0xff)
	green := float64(color >> 8 & 0xff)
	blue := float64(color & 0xff)
	y := int32(0.299*red + 0.587*green + 0.114*blue)
	u := int32(-0.169*red-0.331*green+0.5*blue) + 128
	v := int32(0.5*red-0.419*green-0.081*blue) + 128
	return uint32(y<<16 + u<<8 + v)
}

// yuvDiff reports whether two colors are different enough to be parts of
// different shapes. The thresholds are loose on luma and tight on chroma,
// because an edge the eye reads as an edge is usually a brightness step.
func yuvDiff(first, second uint32) bool {
	const (
		yMask      = 0x00FF0000
		uMask      = 0x0000FF00
		vMask      = 0x000000FF
		yThreshold = 0x00300000
		uThreshold = 0x00000700
		vThreshold = 0x00000006
	)
	return absDiff(int32(first&yMask), int32(second&yMask)) > yThreshold ||
		absDiff(int32(first&uMask), int32(second&uMask)) > uThreshold ||
		absDiff(int32(first&vMask), int32(second&vMask)) > vThreshold
}

func absDiff(first, second int32) int32 {
	if first > second {
		return first - second
	}
	return second - first
}

func diff(first, second uint32) bool {
	return yuvDiff(rgbToYUV(first), rgbToYUV(second))
}

// interpolate2 and interpolate3 are weighted color averages, done on the
// masked channel groups so that two multiplies cover three channels.
func interpolate2(first uint32, firstWeight int32, second uint32, secondWeight int32, shift int32) uint32 {
	if first == second {
		return first
	}
	alpha := uint32((int32(first&maskAlpha>>24)*firstWeight+int32(second&maskAlpha>>24)*secondWeight)<<(24-shift)) & maskAlpha
	green := uint32((int32(first&maskGreen)*firstWeight+int32(second&maskGreen)*secondWeight)>>shift) & maskGreen
	redBlue := uint32((int32(first&maskRedBlue)*firstWeight+int32(second&maskRedBlue)*secondWeight)>>shift) & maskRedBlue
	return alpha + green + redBlue
}

func interpolate3(first uint32, firstWeight int32, second uint32, secondWeight int32, third uint32, thirdWeight int32, shift int32) uint32 {
	alpha := uint32((int32(first&maskAlpha>>24)*firstWeight+int32(second&maskAlpha>>24)*secondWeight+int32(third&maskAlpha>>24)*thirdWeight)<<(24-shift)) & maskAlpha
	green := uint32((int32(first&maskGreen)*firstWeight+int32(second&maskGreen)*secondWeight+int32(third&maskGreen)*thirdWeight)>>shift) & maskGreen
	redBlue := uint32((int32(first&maskRedBlue)*firstWeight+int32(second&maskRedBlue)*secondWeight+int32(third&maskRedBlue)*thirdWeight)>>shift) & maskRedBlue
	return alpha + green + redBlue
}

// The named blends the decision table calls for. The comment on each is the
// unmasked arithmetic it performs.
func interp1(c1, c2 uint32) uint32     { return interpolate2(c1, 3, c2, 1, 2) }        // (c1*3 + c2) / 4
func interp2(c1, c2, c3 uint32) uint32 { return interpolate3(c1, 2, c2, 1, c3, 1, 2) } // (c1*2 + c2 + c3) / 4
func interp3(c1, c2 uint32) uint32     { return interpolate2(c1, 7, c2, 1, 3) }        // (c1*7 + c2) / 8
func interp4(c1, c2, c3 uint32) uint32 { return interpolate3(c1, 2, c2, 7, c3, 7, 4) } // (c1*2 + (c2+c3)*7) / 16
func interp5(c1, c2 uint32) uint32     { return interpolate2(c1, 1, c2, 1, 1) }        // (c1 + c2) / 2
func interp6(c1, c2, c3 uint32) uint32 { return interpolate3(c1, 5, c2, 2, c3, 1, 3) } // (c1*5 + c2*2 + c3) / 8
func interp7(c1, c2, c3 uint32) uint32 { return interpolate3(c1, 6, c2, 1, c3, 1, 3) } // (c1*6 + c2 + c3) / 8
func interp8(c1, c2 uint32) uint32     { return interpolate2(c1, 5, c2, 3, 3) }        // (c1*5 + c2*3) / 8
func interp9(c1, c2, c3 uint32) uint32 { return interpolate3(c1, 2, c2, 3, c3, 3, 3) } // (c1*2 + (c2+c3)*3) / 8
func interp10(c1, c2, c3 uint32) uint32 {
	return interpolate3(c1, 14, c2, 1, c3, 1, 4) // (c1*14 + c2 + c3) / 16
}

// patternFunc writes one source pixel's magnified block.
type patternFunc func(dst []uint32, dstIndex, dstRowElements int, w *[10]uint32, pattern int)

// Scaler magnifies one frame after another, keeping the working buffers
// between calls.
//
// Magnifying a 240x320 frame allocates three planes and an output image —
// 3 MB at hq2x and 10.5 MB at hq4x, measured — and a game presents a frame
// twenty-odd times a second for as long as it is played. That garbage is
// collected on the machine running the emulator, so it is the guest's time it
// costs. Everything a Scaler holds is written from end to end before it is
// read, so keeping it across frames cannot carry a pixel of the last one
// forward: the source planes are filled per pixel, and every destination pixel
// belongs to exactly one source pixel's block.
//
// **What it does not keep is the image it answers with.** That one leaves for
// a Host to hold — this project's server hands it to another goroutine to
// compress — so it is freshly allocated per frame, and reusing it is the one
// change here that would corrupt a frame in flight.
//
// A Scaler is not safe for concurrent use. One belongs to whatever owns the
// frames, which is one session.
type Scaler struct {
	packed []uint32
	yuv    []uint32
	dst    []uint32
}

// plane returns a buffer of exactly count elements, reusing held to the extent
// it is already large enough.
func plane(held []uint32, count int) []uint32 {
	if cap(held) >= count {
		return held[:count]
	}
	return make([]uint32, count)
}

// Scale magnifies src by factor (2, 3, or 4) into a newly allocated image.
// Colors are packed 0xAARRGGBB.
func Scale(src []uint32, width, height, factor int) ([]uint32, error) {
	// A Scaler that holds nothing yet allocates exactly what this always did.
	return (&Scaler{}).scale(src, width, height, factor)
}

func (s *Scaler) scale(src []uint32, width, height, factor int) ([]uint32, error) {
	var apply patternFunc
	switch factor {
	case 2:
		apply = hq2xPattern
	case 3:
		apply = hq3xPattern
	case 4:
		apply = hq4xPattern
	default:
		return nil, fmt.Errorf("hqx factor %d is not 2, 3, or 4", factor)
	}
	if width <= 0 || height <= 0 {
		return nil, fmt.Errorf("hqx source is %dx%d", width, height)
	}
	if len(src) < width*height {
		return nil, fmt.Errorf("hqx source holds %d pixels, %dx%d needs %d", len(src), width, height, width*height)
	}

	s.dst = plane(s.dst, width*factor*height*factor)
	dst := s.dst
	dstRowElements := width * factor
	var w [10]uint32
	// Neighbour YUV, gathered from the plane below rather than converted per
	// neighbour: every pixel is some other pixel's neighbour eight times over,
	// so converting once per pixel instead of nine cuts the float work by that
	// much. The reference implementation avoids it with a 16-million entry
	// lookup table; a plane the size of the image is the same idea without the
	// 64MB.
	var neighbourYUV [10]uint32
	s.yuv = plane(s.yuv, width*height)
	yuv := s.yuv
	for index := 0; index < width*height; index++ {
		yuv[index] = rgbToYUV(src[index])
	}

	for row := 0; row < height; row++ {
		// Edge rows and columns repeat themselves rather than reading outside
		// the image, so a shape touching the border is magnified as if it
		// continued.
		previousRow, nextRow := 0, 0
		if row > 0 {
			previousRow = -width
		}
		if row < height-1 {
			nextRow = width
		}
		srcIndex := row * width
		dstIndex := row * factor * dstRowElements

		for column := 0; column < width; column++ {
			w[2], neighbourYUV[2] = src[srcIndex+previousRow], yuv[srcIndex+previousRow]
			w[5], neighbourYUV[5] = src[srcIndex], yuv[srcIndex]
			w[8], neighbourYUV[8] = src[srcIndex+nextRow], yuv[srcIndex+nextRow]
			if column > 0 {
				w[1], neighbourYUV[1] = src[srcIndex+previousRow-1], yuv[srcIndex+previousRow-1]
				w[4], neighbourYUV[4] = src[srcIndex-1], yuv[srcIndex-1]
				w[7], neighbourYUV[7] = src[srcIndex+nextRow-1], yuv[srcIndex+nextRow-1]
			} else {
				w[1], w[4], w[7] = w[2], w[5], w[8]
				neighbourYUV[1], neighbourYUV[4], neighbourYUV[7] = neighbourYUV[2], neighbourYUV[5], neighbourYUV[8]
			}
			if column < width-1 {
				w[3], neighbourYUV[3] = src[srcIndex+previousRow+1], yuv[srcIndex+previousRow+1]
				w[6], neighbourYUV[6] = src[srcIndex+1], yuv[srcIndex+1]
				w[9], neighbourYUV[9] = src[srcIndex+nextRow+1], yuv[srcIndex+nextRow+1]
			} else {
				w[3], w[6], w[9] = w[2], w[5], w[8]
				neighbourYUV[3], neighbourYUV[6], neighbourYUV[9] = neighbourYUV[2], neighbourYUV[5], neighbourYUV[8]
			}

			// The pattern is one bit per neighbour: set when that neighbour is
			// a different enough color to be a different shape.
			pattern, flag := 0, 1
			center := neighbourYUV[5]
			for neighbour := 1; neighbour < 10; neighbour++ {
				if neighbour == 5 {
					continue
				}
				if w[neighbour] != w[5] && yuvDiff(center, neighbourYUV[neighbour]) {
					pattern |= flag
				}
				flag <<= 1
			}

			apply(dst, dstIndex, dstRowElements, &w, pattern)
			srcIndex++
			dstIndex += factor
		}
	}
	return dst, nil
}

// ScaleRGBA magnifies an RGBA byte image, which is the shape a Host
// framebuffer is in. It answers the scaled bytes and their dimensions.
//
// A Host magnifying frame after frame should hold a Scaler and call this on it
// instead; the answer is the same either way.
func ScaleRGBA(src []byte, width, height, factor int) ([]byte, int, int, error) {
	return (&Scaler{}).ScaleRGBA(src, width, height, factor)
}

// ScaleRGBA magnifies an RGBA byte image, reusing this Scaler's working
// buffers. The bytes it answers with are new every call.
func (s *Scaler) ScaleRGBA(src []byte, width, height, factor int) ([]byte, int, int, error) {
	if len(src) != width*height*4 {
		return nil, 0, 0, fmt.Errorf("hqx source is %d bytes, %dx%d RGBA needs %d", len(src), width, height, width*height*4)
	}
	s.packed = plane(s.packed, width*height)
	packed := s.packed
	for index := range packed {
		offset := index * 4
		packed[index] = uint32(src[offset+3])<<24 | uint32(src[offset])<<16 | uint32(src[offset+1])<<8 | uint32(src[offset+2])
	}
	scaled, err := s.scale(packed, width, height, factor)
	if err != nil {
		return nil, 0, 0, err
	}
	out := make([]byte, len(scaled)*4)
	for index, color := range scaled {
		offset := index * 4
		out[offset] = byte(color >> 16)
		out[offset+1] = byte(color >> 8)
		out[offset+2] = byte(color)
		out[offset+3] = byte(color >> 24)
	}
	return out, width * factor, height * factor, nil
}
